api:
  baseUrl: localhost:1360
  protocol: https

database:
  address: localhost
  username: root
  dbName: superSystem
  rootPassword: mySecret_sUperUzer-password

auth:
  base64TokenSeed: IXRoZXF1aWNrZm94anVtcHNvdmVydGhlbGF6eWRvZyE # 32 bytes wide seed
  bcryptCost: 12