api:
  baseUrl: localhost:1360
  protocol: https

database:
  address: localhost
  username: root
  dbName: superSystem
  rootPassword: mySecret_sUperUzer-password

auth:
  base64TokenSeed: dGhlcXVpY2tmb3hqdW1wc292ZXJ0aGVsYXp5ZG9nIQ== # 32 bytes wide seed
  bcryptCost: 12