---
openapi: '3.0.2'
info:
  title: Go Simple API
  version: '1.0'

servers:
  - url: http://localhost:1360/api/{apiVersion}
    variables:
      "apiVersion":
        default: v1
        enum: [ "v1" ]

tags:
  - name: User
    description: Create, modify, and list users
  - name: Auth
    description: Generate and refresh authentication tokens

paths:
  "/users":
    get:
      description: Return all users from the database
      tags: [ "User" ]
      responses:
        "200":
          description: List of users
          content:
            "application/json":
              schema:
                type: array
                items: { $ref: "#/components/schemas/UserModel" }

  "/user/{id}":
    parameters:
      - name: id
        in: path
        required: true
        schema: { $ref: "#/components/schemas/UserId" }
    get:
      description: A single user from the database by their ID
      tags: [ "User" ]
      responses:
        "200":
          description: User information
          content:
            "application/json":
              schema: { $ref: "#/components/schemas/IdentifiedUser" }
        "404":
          description: User ID was not found in the database
        "400":
          description: Incorrent type for path's parameter "id"
          content:
            "application/json":
              schema: { $ref: "#/components/schemas/ErrorMessage" }

    patch:
      description: Update user information
      tags: [ "User" ]
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              properties:
                "username":
                  type: string
      responses:
        "200":
          description: User was successfully updated
          content:
            "application/json":
              schema: { $ref: "#/components/schemas/IdentifiedUser" }
        "404":
          description: User ID was not found in the database

    delete:
      description: Removes an user from the database
      tags: [ "User" ]
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              properties:
                "password":
                  type: string
                  format: password
      responses:
        "204":
          description: User was successfully removed
        "404":
          description: User ID was not found in the database

  "/user":
    post:
      description: Add a new User to the database
      tags: [ "User" ]
      requestBody:
        required: true
        content:
          "application/json":
            schema: { $ref: "#/components/schemas/UserWithPassword" }
      responses:
        "201":
          description: The brand new User with their ID
          content:
            "application/json":
              schema: { $ref: "#/components/schemas/IdentifiedUser" }
          headers:
            "Location":
              schema:
                type: string
                example: http://localhost:1360/api/v1/user/5
        "400":
          description: Incorrect body data
          content:
            "application/json":
              schema: { $ref: "#/components/schemas/ErrorMessage" }
        "409":
          description: Email address already exist
          content:
            "application/json":
              schema: { $ref: "#/components/schemas/ErrorMessage" }

  "/user/{id}/password":
    parameters:
      - name: id
        in: path
        required: true
        schema: { $ref: "#/components/schemas/UserId" }
    patch:
      description: Change user password
      tags: [ "User" ]
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              properties:
                "lastPassword":
                  type: string
                  format: password
                "newPassword":
                  type: string
                  format: password
              required:
                - "lastPassword"
                - "newPassword"
      responses:
        "204":
          description: Password was changed successfully
        "401":
          description: The last password was incorrect
        "404":
          description: User ID was not found in the database

components:
  schemas:
    "ErrorMessage":
      type: object
      properties:
        "error":
          type: string
    "UserId":
      type: integer
      format: int32
    "UserPassword":
      type: string
      format: password
      maxLength: 72
      minLength: 8
    "UserEmail":
      type: string
      format: email
      maxLength: 100
    "UserName":
      type: string
      minLength: 3
      maxLength: 50
    "JWTString":
      type: string
      format: jwt
    "UserModel":
      type: object
      properties:
        "username":
          $ref: "#/components/schemas/UserName"
        "email":
          $ref: "#/components/schemas/UserEmail"
    "IdentifiedUser":
        type: object
        allOf:
          - $ref: "#/components/schemas/UserModel"
          - $ref: "#/components/schemas/UserId"
    "UserWithPassword":
      type: object
      allOf:
        - $ref: "#/components/schemas/UserModel"
      properties:
        "password":
          $ref: "#/components/schemas/UserPassword"
      required:
        - "username"
        - "email"
        - "password"
    "TokenResponse":
      type: object
      properties:
        "token":
          $ref: "#/components/schemas/JWTString"